config/routes.rb
Estia::Application.routes.draw do
  
  resources :users
  resources :listings
  resources :sessions
  resources :password_resets
  
  root to: 'static_pages#home'
  
  match 'signup', to: 'users#new'
  match 'login', to: 'sessions#new'
  match 'logout', to: 'sessions#destroy'  
  
  match '/about', to: 'static_pages#about'
  match '/how_it_works', to: 'static_pages#how_it_works'
  match '/support', to: 'static_pages#support'
  match '/jobs', to: 'static_pages#jobs'
  match '/news', to: 'static_pages#news'
  match '/terms_and_conditions', to: 'static_pages#terms_and_conditions'
  
 
  match 'contact' => 'messages#new', :as => 'messages', :via => :get
  match 'contact' => 'messages#create', :as => 'messages', :via => :post
  
  

  

end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id             :integer          not null, primary key
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  title          :string(255)
#  description    :text
#  property_type  :string(255)
#  bedrooms       :integer
#  bathrooms      :integer
#  address_line_1 :string(255)
#  address_line_2 :string(255)
#  city           :string(255)
#  state          :string(255)
#  zip_code       :integer
#  country        :string(255)
#  user_id        :integer
#

class Listing < ActiveRecord::Base
  attr_accessible :title, :description, :property_type, :bedrooms, :bathrooms, :address_line_1,
                  :address_line_2, :city, :state, :country, :zip_code, :listing_photos_attributes
  belongs_to :user
  has_many :listing_photos, dependent: :destroy
  accepts_nested_attributes_for :listing_photos, :allow_destroy => true
  
  
  
  validates :user_id, presence: true
  validates :title, length: { minimum: 3, maximum: 50 }
  validates :description, length: { minimum: 10, maximum: 500 }
  validates :property_type, presence: true
  validates :bedrooms, presence: true
  validates :bathrooms, presence: true
  validates :address_line_1, presence: true
  #validates :address_line_2, presence:true  #can be blank so no need for validation
  validates :city, length: { minimum: 2 }
  validates :state, presence: true
  validates :zip_code, length: { minimum: 5 }
  validates :country, length: { minimum: 3 }
  
  
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  before_filter :signed_in_user,
  only: [:show, :new]
  def index
    @listings = Listing.order("created_at DESC").page(params[:page]).per_page(4)
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def new
    @listing = Listing.new 
  end

  def create
    @listing = current_user.listings.build(params[:listing])
    if @listing.save
      redirect_to @listing, :flash => { :success => "Your listing is now live on the web. Congrats!"}
    else
      render "new"
    end
  end

  def edit
    @listing = Listing.find(params[:id])
    10.times {@listing.listing_photos.build}
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update_attributes(params[:listing])
      flash[:success] = "Listing updated"
      redirect_to @listing
    else
      render 'edit'
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    if @listing.destroy
      flash[:success] = "Listing has been removed"
      redirect_to current_user
    else
      flash[:error] = "Oups! Something went wrong"
      redirect_to edit_listing_path(@listing)
    end
  end
  
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/edit.html.erb
<% provide(:title, "Edit Project") %> 
<legend>Edit Listing</legend>
<div class="row">
	<div class="span6 offset3">


		<%= form_for @listing, :html => { :multipart => true } do |f| %>

		<%= render 'layouts/error_messages', object: f.object %>

		<legend>Listing Edit</legend>

		<%= f.label :title, "Title" %>
		<%= f.text_field :title, :maxlength => 50, :class => "span4" %>

		<%= f.label :property_type, "Property Type" %>
		<%= f.select :property_type, [ 'Room', 'Apartment', 'House', 'Villa', 'Car', 'Yacht' ], :prompt => '' %>

		<%= f.label :bedrooms, "Bed Rooms" %>
		<%= f.select :bedrooms, [ '1', '2', '3', '4', '5', '6' ], :prompt => ''  %>

		<%= f.label :bathrooms, "Bath Rooms" %>
		<%= f.select :bathrooms, [ '1', '2', '3', '4', '5', '6' ], :prompt => ''  %>

		<%= f.label :description, "Description"%>
		Characters left: <span id="char-count">400</span>
		<%= f.text_area :description, :maxlength => 400, :rows => 8, :class => "span6", :placeholder => "This is where you would write why you're place is awesome! (Maximum of 400 characters)" %>

		<legend >Address Information</legend>

		<%= f.label :address_line_1, "Address Line 1" %>
		<%= f.text_field :address_line_1 %>

		<%= f.label :address_line_2, "Address Line 2" %>
		<%= f.text_field :address_line_2 %>

		<%= f.label :city, "City" %>
		<%= f.text_field :city %>

		<%= f.label :state, "State" %>
		<%= f.text_field :state %>

		<%= f.label :country, "Country" %>
		<%= f.select :country, [ 'Cyprus', 'Greece', 'Japan', 'United Kingdom', 'United States'], :prompt => '' %>

		<%= f.label :zip_code, "Zip Code" %>
		<%= f.text_field :zip_code, maxlength: 5 %>

		<%= f.fields_for :listing_photos do |listing_photo| %>

			<% if listing_photo.object.new_record? %>
				<%= listing_photo.file_field :photo %>
			<% end %>

		<% end %>
		
		<legend>Below are your uploaded photos (if any exist)</legend>
		<p>To delete images, check the box and hit save.</p>
		
		
		<%= f.fields_for :listing_photos do |listing_photo| %>
       
    		<% unless listing_photo.object.new_record? %>
       
    		<%= link_to image_tag(listing_photo.object.photo.url(:thumb)), listing_photo.object.photo.url(:original) %>
                       <%= listing_photo.check_box :_destroy %>
               
         <% end %>        
       
    <% end %>

		<div class="form-actions">
			<%= f.submit "Save", class: "btn btn-primary" %>
			<%= link_to "Cancel", listing_path, class: "btn"%>
		</div>

	<%end%>
			
	</div>

</div>					




<script type="text/javascript">	
var maxLen = 400;
$(function() { setCharCount($('#listing_description'));	}); 
$('#listing_description').live('keyup keydown', function(e) { setCharCount($(this));	});	 
function setCharCount(object) {	 var left = maxLen - object.val().length;	 $('#char-count').html(left);	}
</script>

app/views/listings/index.html.erb
<legend>Listings</legend>

<% for listing in @listings %>
	<div class="well">
		<h4><%= link_to listing.title, listing %><h4>
		<h5><%= listing.description %><h5>
	</div>
<% end %>

<%= will_paginate @listings, class: "apple_pagination" %>

app/views/listings/new.html.erb
<div class="span8 offset2">
	<legend >Basic Property Information</legend>
	<div class="well" id="gray">

		<%= form_for(@listing, :html => { :multipart => true }, :url => {:controller => 'listings', :action => 'create'}) do |f| %>

		<%= render 'layouts/error_messages', object: f.object %>
		
		<%= f.label :title, "Title" %>
		<%= f.text_field :title, :maxlength => 50, :class => "span4" %>

		<%= f.label :property_type, "Property Type" %>
		<%= f.select :property_type, [ 'Room', 'Apartment', 'House', 'Villa', 'Car', 'Yacht' ], :prompt => '' %>

		<%= f.label :bedrooms, "Bed Rooms" %>
		<%= f.select :bedrooms, [ '1', '2', '3', '4', '5', '6' ], :prompt => ''  %>

		<%= f.label :bathrooms, "Bath Rooms" %>
		<%= f.select :bathrooms, [ '1', '2', '3', '4', '5', '6' ], :prompt => ''  %>

		<%= f.label :description, "Description"%>
		<%= f.text_area :description, :maxlength => 400, :rows => 8, :class => "span6", :placeholder => "This is where you would write why you're place is awesome! (Maximum of 500 characters)" %>

	</div>


	<legend >Address Information</legend>
	<div class="well" id="gray">

		<%= f.label :address_line_1, "Address Line 1" %>
		<%= f.text_field :address_line_1 %>

		<%= f.label :address_line_2, "Address Line 2" %>
		<%= f.text_field :address_line_2 %>
		
		<%= f.label :city, "City" %>
		<%= f.text_field :city %>
		
		<%= f.label :state, "State" %>
		<%= f.text_field :state %>
		
		<%= f.label :country, "Country" %>
		<%= f.select :country, [ 'Cyprus', 'Greece', 'Japan', 'United Kingdom', 'United States'], :prompt => '' %>

		<%= f.label :zip_code, "Zip Code" %>
		<%= f.text_field :zip_code, maxlength: 5 %>

	</div>

	<div class="form-actions ">
		<%= link_to "Cancel", root_path, :class => "btn"%>
		<%= f.submit "List Property", class: "btn btn-warning", style: "font-weight: bold;"%>

	</div>

	<% end %>

</div>

app/views/listings/show.html.erb
<legend><%=link_to @listing.title, edit_listing_path%></legend>