config/routes.rb
Estia::Application.routes.draw do
  
  resources :users
  resources :listings
  resources :sessions
  resources :password_resets
  
  root to: 'static_pages#home'
  
  match 'signup', to: 'users#new'
  match 'login', to: 'sessions#new'
  match 'logout', to: 'sessions#destroy'  
  
  match '/about', to: 'static_pages#about'
  match '/how_it_works', to: 'static_pages#how_it_works'
  match '/support', to: 'static_pages#support'
  match '/jobs', to: 'static_pages#jobs'
  match '/news', to: 'static_pages#news'
  match '/terms_and_conditions', to: 'static_pages#terms_and_conditions'
  
 
  match 'contact' => 'messages#new', :as => 'messages', :via => :get
  match 'contact' => 'messages#create', :as => 'messages', :via => :post
  
  

  

end

app/views/layouts/_default_header.html.erb
<%= link_to image_tag("estia_logo.png", :class => 'header_logo'), root_path %>
<ul class="nav pull-right" style="margin-top:15px; display:inline-block;">

		<%= link_to "Sign In", login_path, :class=>'btn nav-button' %>

		<%= link_to "Sign Up", signup_path, :class=>'btn btn-primary nav-button' %>

		<%= link_to "List Property", new_listing_path, :class=>'btn btn-warning nav-button' %>

</ul>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
<div class="error_explanation">
	<div class="alert alert-error">
		The form contains <%= pluralize(object.errors.count, "error") %>:
		<ul>
			<% object.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="navbar">
		<div class="span9 center">	
			<ul class="nav">
				<li><%= link_to "About", about_path %> </li>
				<li><%= link_to "How It Works", how_it_works_path %> </li>
				<li><%= link_to "Support Us", support_path %> </li>
				<li><%= link_to "Jobs", jobs_path %> </li>
				<li><%= link_to "News", news_path %></li>
				<li><%= link_to "Terms", terms_and_conditions_path %></li>
				<li><%= link_to "Contact Us", messages_path %></li>
			</ul>
		</div>
		<p id="Copyright">Copyright &copy 2013 Estia LLC. All rights reserved.</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-static-top">
	<div class="navbar-inner">
			<% if current_user %>
				<%= render 'layouts/signed_in_header'%>
			<% else %>
				<%= render 'layouts/default_header'%>
			<% end %>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_signed_in_header.html.erb
<% username = current_user.first_name + " " + current_user.last_name %>

<%= link_to( image_tag("estia_logo_color.png", :class => 'header_logo'), root_path) %>

<div class="nav pull-right">

	<%= link_to "Browse", listings_path, :class=>'btn btn-success', style: "font-weight: bold;" %>
	
	<%= link_to username, current_user, :class=>'btn nav-button' %>

	<a href="#" class="btn btn-inverse dropdown" style="font-weight: bold;" data-toggle="dropdown">
		Account <b class="caret"></b>
	</a>
	
	<ul class="dropdown-menu">
		<li><%= link_to "Settings", edit_user_path(current_user) %></li>
		<li class="divider"></li>
		<li><%= link_to "Log Out", logout_path%></li>
	</ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title))%></title>
	<%= favicon_link_tag 'favicon.ico'%>
	<%= metamagic %>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
</head>

<body>
	<div class="wrapper">
		<%= render 'layouts/header'%>

		<% if current_page?('/') %>
		<%= render 'static_pages/partials/carousel'%>
		<% end %>

		<div class="container" style="padding-top: 20px;">
			<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>">
				<div class= "offset4">
					<%= value %>
				</div>
			</div>
			<% end %>

			<%= yield %>

		</div>
		<div class="push"></div>
	</div><!-- wrapper finish -->

	<%= render 'layouts/footer' %>
</body>
</html>